### ISSUE TITLE
[BUG] Can't load plugin

### ISSUE THREAD

**Issue by BigDi** [The-EG/OctoPrint-UBLMeshEdit#15]
The plugin creates errors while installing.

```
2021-05-19 16:09:19,600 - octoprint.plugin.core - ERROR - Invalid syntax in /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_ublmeshedit/__init__.py for plugin ublmeshedit
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 711, in _parse_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_ublmeshedit/__init__.py", line 101
    self._logger.info(f'got mesh row: {row}')
                                           ^
SyntaxError: invalid syntax
2021-05-19 16:09:19,667 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2021.3.26.post2) did not pass check, not loading.
2021-05-19 16:09:19,736 - octoprint.plugin.core - ERROR - Error loading plugin eeprom_marlin
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1264, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_eeprom_marlin/__init__.py", line 17, in <module>
    from octoprint_eeprom_marlin import (
ImportError: cannot import name _version
2021-05-19 16:09:30,233 - octoprint.plugin.core - ERROR - Invalid syntax in /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_ublmeshedit/__init__.py for plugin ublmeshedit
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 711, in _parse_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_ublmeshedit/__init__.py", line 101
    self._logger.info(f'got mesh row: {row}')
                                           ^
SyntaxError: invalid syntax
2021-05-19 16:09:30,289 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2021.3.26.post2) did not pass check, not loading.
2021-05-19 16:09:30,357 - octoprint.plugin.core - ERROR - Error loading plugin eeprom_marlin
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1264, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_eeprom_marlin/__init__.py", line 17, in <module>
    from octoprint_eeprom_marlin import (
ImportError: cannot import name _version
```

**Comment by The-EG** [comment]
Ah, this may be a Python2 issue...hard to believe you are the first to use the plugin with Python 2, however. I'll take a look!

**Comment by The-EG** [comment]
Please install the latest version of the plugin, 0.3.2. This should now be fixed.

**Comment by BigDi** [comment]
Thanks. Plugin starts now. BTW: It shows values but the bed level visualizer plugin shows completely different values. It also shows correct values (NA) in the corners for my delta printer.

**Comment by The-EG** [comment]
I don't have a delta printer so feedback there would be good. I can't really speak to BLV, since that's a different plugin with different goals (BLV is more for seeing the overall orientation of the bed, this plugin is intended for manually editing the individual values).
